### ISSUE TITLE
[BUG] Not showing "real" AdMob button

### ISSUE THREAD

**Issue by KinashMaksym** [Poing-Studios/godot-admob-editor#16]
**Godot and Plugin Version 3.3.4 / 1.1.0 **

**Computer Specification (Operational System, CPU, GPU and Resolution(1920x1080)**
- OS: [Windows 10]

**Phone Specification (Android)**
- Device: [Xiaomi 9C]

**Describe the bug**
I cant find real admob button. So banner always test on Android

**Screenshots**

![image_2021-10-16_18-27-35](https://user-images.githubusercontent.com/45206635/137595188-1b42c744-9ae9-4d9e-b2a4-1515fd400a73.png)

**Additional context**

**Comment by wongselent** [comment]
You can read this for the solution https://github.com/Poing-Studios/godot-admob-editor/issues/6#issue-976547847

**Comment by gumaciel** [comment]
@KinashMaksym Hi, now the Plugin automatic detect if you are running on `debug` or `release` mode, if `debug` then you are testing, else if `release` (production), then you are not testing.

I can put an option to you select Manual or Automatic if is testing or not, what you think?

**Comment by KinashMaksym** [comment]
I check it and that work. Thank you )

нд, 17 жовт. 2021, 23:52 користувач Gustavo Maciel ***@***.***>
пише:
