### ISSUE TITLE
[BUG] godot admob android with c# gives black screen and hangs on android

### ISSUE THREAD

**Issue by almunsaah** [Poing-Studios/godot-admob-editor#19]
I used this plugin to add ads to my game( using c#) and when I run my game on android device gives me black screen and hangs, I thought maybe the problem in my code but every thing is fine, so I tried to check test scene which comes with the plugin, I made new project contains only test scene which come with plugin and and replaced gd script by c#  script(coming with plugin in test folder) after creating project solution, and checked the project on android, also gave me same result (Black screen and hangs).
Returning to gd script make project works and show ads, but using c# fails.
I followed all c# bugs for this plugin but I can't find any solution, should I use gd script?, I never use it!!!!

**Comment by gumaciel** [comment]
@almunsaah Please test with this new version of Editor Plugin: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.2.0


Obs: Try the Example.tscn and change the Script to "Example.cs"

**Comment by almunsaah** [comment]
It works, thank you very much. 
I tested example project (mono version, c# file "example.cs"), works on android and shows ads, No black screen...No Hanging.
Thank you.

**Comment by gumaciel** [comment]
Thank you! Closing the issue since is fixed
