### ISSUE TITLE
Have been encountering " Task :mergeDebugResources FAILED " error. Have tried a lot of things but can't get over it. [BUG] 

### ISSUE THREAD

**Issue by ajk2196** [Poing-Studios/godot-admob-editor#27]
**Godot and Plugin Version**

**Computer Specification (Operational System, CPU, GPU and Resolution(1920x1080)**
- Windows 10
- AMD 3700X
- 2x RTX 2070 Super
- 1920x1080
- Godot Admob Editor Version 1.2.4
- Android Standard Template v3.4.4

**Describe the bug**
I want to use this plugin in order to enable the ads in my project. However, when I enable it, I get the following error (Screenshot Attached) when I try to export the Android APK, and doesn't let me successfully create the APK. I have tried a couple of things to avoid this problem, like:

1. Changing the resources in the mentioned hidpi folder to JPG formats.
2. Using the cruncher settings:
    **aaptOptions.cruncherEnabled = false
    aaptOptions.useNewCruncher = false**
3. Changing the directory in order to keep the file path under 260 characters.

There is no way apparent to me that would help me to come over this issue. Kindly please help, this is important to me.

**However, when I disable the custom build and the Admob plugin from the Exports preset, I do not find any error and the app exports sucessfully, but its of no use as there is no Admob in it.**

**To Reproduce**
Use the plugins and editor versions the same as above to replicate my case.

**Screenshots**
![ErrorSS](https://user-images.githubusercontent.com/90527174/172975634-17d70978-998c-40c3-a737-6f5908ddf728.jpg)

**Comment by gumaciel** [comment]
Hi, sorry for delay, if you disable the Plugin `Ad Mob` to export, the exports works?

I can't see any reference of our Plugin causing this error, what Godot version are you using?

**Comment by ajk2196** [comment]
No Problem. Yes, the app exports successfully if I disable the plugin. Here is a video of it. The Godot version I am using is 3.4.4 stable, visible in the video's bottom part.

The Video:

https://user-images.githubusercontent.com/90527174/173168033-bccd1c0f-5f1d-4797-9621-6ef8bdf95694.mp4

**Comment by gumaciel** [comment]
Hi, just saw the video now, you are exporting with the `Use Custom Build` disabled, please try to export with `Use Custom Build` enabled and `Ad Mob` disabled

Other thing: Try to export your game outside your game source folder

**Comment by ajk2196** [comment]
Ok @gumaciel . I tried everything you just suggested. Here is the video. It is still not working.

https://user-images.githubusercontent.com/90527174/173181338-39666bdf-cbdb-41cb-8e7d-6dc9bac743e3.mp4

.

I tried to export in both source folder and outside the source folder, as recorded in the video. Problem still persists. Please help.

**Comment by gumaciel** [comment]
Also try exporting an empty project with `Use Custom Build` enabled to see if it works, if it works, add our Plugin and test with this scene: https://github.com/Poing-Studios/godot-admob-editor/blob/master/addons/admob/test/Example.tscn
