### ISSUE TITLE
[FEATURE] Should have is_rewarded_video_loaded & is_interstitial_loaded

### ISSUE THREAD

**Issue by kyoz** [Poing-Studios/godot-admob-editor#3]
**Describe the solution you'd like**

There should be an api to check if there is reward video loaded. Because sometime reward videos doesn't load new video after user watch first one.

With this api, we can easily detect if there's not reward video and let user know.

Something like:

```
is_interstitial_loaded()
is_rewarded_video_loaded()
```

**Comment by gumaciel** [comment]
Hey @kyoz please try to use the new version 0.4.0:

https://github.com/Poing-Studios/godot-admob-editor/releases/tag/0.4.0

Ps: You need to update the Android and iOS Plugin

**Comment by kyoz** [comment]
Hi @gumaciel, Tested it out on 2 phones and work great, the new Editor UI is great.

Btw, there's an child directed treatment option, is it a must if my app is rated for 3+ (even it's not for kids).

Have read [google guide](https://support.google.com/admanager/answer/3671211?hl=en) about this but i doesn't understand clearly what it does :smile: . Do you have any experience about this

**Comment by gumaciel** [comment]
Hi @kyoz read more about Child Directed Treatment here: https://developers.google.com/admob/android/targeting#child-directed_setting

We will need to change the code to add `TAG_FOR_CHILD_DIRECTED_TREATMENT_UNSPECIFIED`, i guess this is something new.

Right now our source code is only treating with `TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE` and `TAG_FOR_CHILD_DIRECTED_TREATMENT_FALSE`: https://github.com/Poing-Studios/godot-admob-android/blob/master/admob/src/main/java/com/poing/admob/AdMob.java#L267

**Comment by kyoz** [comment]
Thanks @gumaciel , i'll update to test it out. :cat:
