### ISSUE TITLE
Installation instructions should prefer asset library

### ISSUE THREAD

**Issue by nathanfranke** [Poing-Studios/godot-admob-editor#33]
**Is your feature request related to a problem? Please describe.**
Manual installation is unnecessary, since the asset library is built in and is usually up to date

**Describe the solution you'd like**
I would just swap around the instructions in the README and add a note that the manual installation is only needed if you are using bleeding edge versions.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by gumaciel** [comment]
Thank you! I believe that once your PR is approved it will solve this problem
