### ISSUE TITLE
[BUG] Test Ads Still Appearing in App When "Real" is Checked.

### ISSUE THREAD

**Issue by ACB-prgm** [Poing-Studios/godot-admob-editor#5]
**Godot and Plugin Version**

**Computer Specification (Operational System, CPU, GPU and Resolution(1920x1080)**
- OS: [e.g. Catalina]
- Version [e.g. 10.15.7 (19H15)]

**Phone Specification (Android/iOS and Version)**
- Device: [e.g. iPhoneX]

**Describe the bug**
Ads still appearing in test mode despite "real" being checked

**To Reproduce**
Add enable real ads and export to IPhone.

**Expected behavior**
real ads to be shown

**Screenshots**

**Additional context**
I have just re-exported and ensured "real" is checked and made sure to export as a release.  I submitted it to the app store for review so I'll let you know when I am approved and if the problem persists on my new version.  The app is about 3 weeks old now so it is weird that they are no appearing as real.

**Comment by gumaciel** [comment]
Hi, have you done this?

On `Export -> Resources -> Filters to export non-resources...`, you need to put this: `res://addons/admob/*.json`

**Comment by ACB-prgm** [comment]
> res://addons/admob/*.json

Nope!  Thank you!

**Comment by gumaciel** [comment]
Sorry about that, I need to re do the video tutorial because it's missing this.

**Comment by ACB-prgm** [comment]
I am getting an error in Xcode now when I try to build however.  I don't have time to look through it right now, but here it is:

Error:
Undefined symbols for architecture x86_64:
  "ClassDB::bind_methodfi(unsigned int, MethodBind*, char const*, Variant const**, int)", referenced from:
      AdMob::_bind_methods() in admob.a(admob.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Output:
Ld /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Products/Debug-iphonesimulator/FishBowl.app/FishBowl normal (in target 'FishBowl' from project 'FishBowl')
    cd /Users/aaronbastian/Documents/Godot_Code/FishBowl.nosync/Exports/IOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios12.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Products/Debug-iphonesimulator -L. -LFishBowl -LFishBowl/dylibs -LFishBowl/ios -LFishBowl/dylibs/ios -LFishBowl/ios/plugins -LFishBowl/dylibs/ios/plugins -LFishBowl/ios/plugins/admob -LFishBowl/dylibs/ios/plugins/admob -LFishBowl/ios/plugins/admob/bin -LFishBowl/dylibs/ios/plugins/admob/lib -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework/ios-arm64_i386_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_i386_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_x86_64-maccatalyst -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/macos-arm64_x86_64 -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/tvos-arm64 -LFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/tvos-arm64_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_i386_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_x86_64-maccatalyst -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/macos-arm64_x86_64 -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/tvos-arm64 -LFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/tvos-arm64_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_armv7 -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_i386_x86_64-simulator -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_x86_64-maccatalyst -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/macos-arm64_x86_64 -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/tvos-arm64 -LFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/tvos-arm64_x86_64-simulator -F/Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Products/Debug-iphonesimulator -F. -FFishBowl -FFishBowl/dylibs -FFishBowl/ios -FFishBowl/dylibs/ios -FFishBowl/ios/plugins -FFishBowl/dylibs/ios/plugins -FFishBowl/ios/plugins/admob -FFishBowl/dylibs/ios/plugins/admob -FFishBowl/ios/plugins/admob/bin -FFishBowl/dylibs/ios/plugins/admob/lib -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleAppMeasurement.xcframework/ios-arm64_i386_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleMobileAds.xcframework/ios-arm64_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_i386_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/ios-arm64_x86_64-maccatalyst -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/macos-arm64_x86_64 -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/tvos-arm64 -FFishBowl/dylibs/ios/plugins/admob/lib/GoogleUtilities.xcframework/tvos-arm64_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_i386_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/ios-arm64_x86_64-maccatalyst -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/macos-arm64_x86_64 -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/tvos-arm64 -FFishBowl/dylibs/ios/plugins/admob/lib/PromisesObjC.xcframework/tvos-arm64_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_armv7 -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_i386_x86_64-simulator -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/ios-arm64_x86_64-maccatalyst -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/macos-arm64_x86_64 -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/tvos-arm64 -FFishBowl/dylibs/ios/plugins/admob/lib/nanopb.xcframework/tvos-arm64_x86_64-simulator -filelist /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Intermediates.noindex/FishBowl.build/Debug-iphonesimulator/FishBowl.build/Objects-normal/x86_64/FishBowl.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Intermediates.noindex/FishBowl.build/Debug-iphonesimulator/FishBowl.build/Objects-normal/x86_64/FishBowl_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -stdlib\=libc++ -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Intermediates.noindex/FishBowl.build/Debug-iphonesimulator/FishBowl.build/FishBowl.app-Simulated.xcent /Users/aaronbastian/Documents/Godot_Code/FishBowl.nosync/Exports/IOS/FishBowl.a /Users/aaronbastian/Documents/Godot_Code/FishBowl.nosync/Exports/IOS/FishBowl/ios/plugins/admob/bin/admob.a -framework nanopb -framework GoogleAppMeasurement -framework GoogleMobileAds -framework GoogleUtilities -framework UserMessagingPlatform -framework PromisesObjC -framework JavaScriptCore -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Intermediates.noindex/FishBowl.build/Debug-iphonesimulator/FishBowl.build/Objects-normal/x86_64/FishBowl_dependency_info.dat -o /Users/aaronbastian/Library/Developer/Xcode/DerivedData/FishBowl-dndohfbrrdlpijejmaeldfpzfrpi/Build/Products/Debug-iphonesimulator/FishBowl.app/FishBowl

**Comment by gumaciel** [comment]
What iOS Plugin and Editor Plugin version are you using?

**Comment by ACB-prgm** [comment]
0.30

**Comment by gumaciel** [comment]
Please consider to use at least the 0.4.0, but I recommend the 0.4.2 (latest) 


And the iOS: 1.1.0

**Comment by ACB-prgm** [comment]
> Please consider to use at least the 0.4.0, but I recommend the 0.4.2 (latest)
> 
> And the iOS: 1.1.0

Using 0.4.1, now nothing happens when the ads should show?  Nothing else changed on my end.  
I am loading the ads via 
```
func _on_admob_init_complete(status, _adapter_name):
	if status == MobileAds.INITIALIZATION_STATUS.READY:
		MobileAds.load_interstitial()
		MobileAds.load_rewarded()

```
and then calling them via the show_Xad functions.

Any ideas?

**Comment by gumaciel** [comment]
Hi, have you changed the iOS Plugin version for 1.1.0?

If so, please try with the "Example.tscn" located on `addons/admob/develop` to see if is working fine

**Comment by ACB-prgm** [comment]
I am now using the ios 1.1.0 for 3.3.2 (my version of Godot).   But I get the following error from the Xcode debug console:
```
2021-08-16 13:58:45.646147-0400 FishBowl[446:24813] init admob plugin
2021-08-16 13:58:45.646307-0400 FishBowl[446:24813] initialize admob
2021-08-16 13:58:45.658532-0400 FishBowl[446:25026]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-8477102077683085~2197552267
2021-08-16 13:58:45.664379-0400 FishBowl[446:25035]  - <Google>[I-ACS023007] Analytics v.80000000 started
2021-08-16 13:58:45.664759-0400 FishBowl[446:25035]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2021-08-16 13:58:45.676813-0400 FishBowl[446:25031]  - <Google>[I-ACS023171] Resetting App Measurement data
2021-08-16 13:58:45.684802-0400 FishBowl[446:25032]  - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/96817A88-74E1-4A99-B2EC-A966C57D3764/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x2838b4720 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2021-08-16 13:58:45.791612-0400 FishBowl[446:24813] AdMob Module not initialized
2021-08-16 13:58:45.792711-0400 FishBowl[446:24813] maxAdContentRating = GADMaxAdContentRatingParentalGuidance
2021-08-16 13:58:45.884164-0400 FishBowl[446:24813] WF: === Starting WebFilter logging for process FishBowl
2021-08-16 13:58:45.884216-0400 FishBowl[446:24813] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-08-16 13:58:45.884253-0400 FishBowl[446:24813] WF: _WebFilterIsActive returning: NO
2021-08-16 13:58:48.073244-0400 FishBowl[446:24813] GADMobileAds : 0
2021-08-16 13:58:52.051524-0400 FishBowl[446:25031]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-08-16 13:58:52.382471-0400 FishBowl[446:25031]  - <Google>[I-ACS023012] Analytics collection enabled
2021-08-16 13:59:00.295615-0400 FishBowl[446:25069]  - <Google>[I-ACS012056] Transaction failed. Transaction failed
```

And nothing happens when an ad is pressed.

**Comment by gumaciel** [comment]
Have you updated the `googlemobileadssdk.zip`?

I will try to run on my Mac now to see what happens

**Comment by ACB-prgm** [comment]
> Have you updated the `googlemobileadssdk.zip`?

I did.  I also made sure to go through the info.plist and make sure everything was correct.

**Comment by gumaciel** [comment]
Probably you configured something wrong, always test with the "Example Ids"

https://developers.google.com/admob/ios/test-ads#demo_ad_units

https://developers.google.com/admob/ios/quick-start#update_your_infoplist

**Comment by gumaciel** [comment]
@ACB-prgm 

Please watch to this tutorial: https://www.youtube.com/watch?v=MW4hUR0d9lc&ab_channel=PoingStudios

**Comment by gumaciel** [comment]
Is there anything you are finding complicated using the Plugin?

I know the Tutorial is not good, but it's just me to make these videos and it's a lot for one person to do, but I hope it helps you.

**Comment by gumaciel** [comment]
@ACB-prgm just send a new update on [master branch](https://github.com/Poing-Studios/godot-admob-editor/commit/201f39d6fe4c81f39fd2afdaf9bb5148676dd7dc) to only set to Real when is on release mode, please test it if you can.

**Comment by gumaciel** [comment]
@ACB-prgm big update released with this update: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.0.0

Soon you will can test here: https://godotengine.org/asset-library/asset/933

**Comment by gumaciel** [comment]
Closing the issue due the age, if something is not working properly please open it again
