### ISSUE TITLE
Crash when opening game on godot 3.5

### ISSUE THREAD

**Issue by Roober123** [Poing-Studios/godot-admob-editor#53]
### Godot version

3.5

### Plugin version

1.3.2

### System information

windows 10

### Phone information, if applicable

Realme gt Android12

### Issue description

if i enable admob plugin from export settings, after export,when i try to open the game on phone it crashes.

### Steps to reproduce

Export on godot 3.5 with admob 1.3.2 enabled and open the game.

**Comment by gumaciel** [comment]
Please test with the latest plugin versions to check if still happens:

https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.3.2
https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.1.2

**Comment by gumaciel** [comment]
Hi @Roober123 the issue persists even updating the plugins?

If so, try to export with these two scenarios:

1. Export without Admob Plugin Editor
- Delete this folder: res://addons/admob/
- Or disable the Plugin on Project -> Project Settings -> Plugins -> AdMob -> Unmark 'Enable'
2. Export without AdMob Plugin Android
- Go to Project -> Export -> Android -> Plugins -> Android -> Unmark

And tell us what scenario the app crashes, thank you!

**Comment by Roober123** [comment]
It worked when i downloaded the updated version . Thank you !

**Comment by gumaciel** [comment]
Thank you! I will close this Issue since it's already fixed on newest version.
