### ISSUE TITLE
 Admob App ID and Unitid's are possible to change their values after the application is compiled?

### ISSUE THREAD

**Issue by mrParabol** [Poing-Studios/godot-admob-editor#55]
### Is your feature request related to a problem? If so, please describe.

I did the Godot game and compiled it as apk. How can I change Admob App ID and Unitid information from the application?  Is it possible to use the Admob App ID and unitid dynamically?

### What feature or improvement would you like to see?

I did the Godot game and compiled it as apk. How can I change Admob App ID and Unitid information from the application?  Is it possible to use the Admob App ID and unitid dynamically?

**Comment by gumaciel** [comment]
Closing this issue since seems to be solved
